Repository jmathai/elodie, pull requests merged in 2019-01, with the labels that each got.

#283 Add support for a %custom placeholder for more complex folder names than %location or %date provide #279
  .gitignore
  Readme.md
  elodie/filesystem.py
  elodie/tests/filesystem_test.py
Labels: do not merge, tests

#225 Add support for customizing file name via config file. #107 #110 #111
  Readme.md
  elodie/filesystem.py
  elodie/tests/files/Plain With Spaces And Uppercase 123.jpg
  elodie/tests/filesystem_test.py
Labels: do not merge, enhancement

#295 MTS video files support
  elodie/media/video.py
Labels: enhancement
